# Generated by Django 5.1.3 on 2024-11-14 18:48

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[profiles.models.validate_iranian_phone_number]),
        ),
    ]
